import { Providers } from './Providers'
import { Tabs } from './Tabs'
import './globals.css'
import { Chivo_Mono, Montserrat } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  variable: '--font-montserrat',
  display: 'swap',
  subsets: ['latin'],
})

const chivoMono = Chivo_Mono({
  variable: '--font-chivo-mono',
  display: 'swap',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable} ${chivoMono.variable}`}>
      <body className="min-h-screen">
        <Providers>
          <div className="max-w-xl mx-auto mt-48">
            <Tabs />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
